name: Flash

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
      - name: Set up Haxelib dependencies
        run: haxelib install all
      - name: Build libraries
        run: haxe build.hxml