name: Flash

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
      - name: Set up Haxelib dependencies
        run: |
          haxelib install haxe-crypto 0.0.7
          haxelib install colyseus-websocket 1.0.12
          haxelib install hxjava
      - name: Build libraries
        run: haxe build.hxml
      - uses: actions/upload-artifact@v3
        with:
           name: sfs2x.js
           path: bin/sfs2x.js
           if-no-files-found: error
      - name: Zip files
        run: |
          cd bin/php
          7z a -tzip ../sfs2x.php.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: sfs2x.jar
          path: bin/sfs2x.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: sfs2x.lua
          path: bin/sfs2x.lua
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: sfs2x.py
          path: bin/sfs2x.py
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: sfs2x.swc
          path: bin/sfs2x.swc
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: sfs2x_full.swc
          path: bin/sfs2x_full.swc
          if-no-files-found: error